### ISSUE TITLE
Problems with running the draft reconstruction

### ISSUE THREAD

**Issue by GwennyGit** [ParkinsonLab/Architect#2]
Hello,

**Installation & problems**
I downloaded and installed Architect as described for the Docker installation. The installation took a while and I had to reinstall the program on another computer as EnzDP was not downloaded. I think this issue was space-related as the other computer had more space left on its hard drive. For the user, it would be good to know how much space is required to be able to install all programs. After that, I encountered the same problem as described in issue #1 which means I was also not able to install PRIAM. 

**Running the program & problems**
Running the program for the enzyme tools which I could install worked without any problem. However, for the second run, the draft reconstruction run, I encountered some problems:
- First of all, it is not clear from your description in the GitHub README that a biomass objective function needs to be provided by the user. 
- Moreover, the file `USER_def_reax` is required as the biomass objective function definition has to be provided with it. Thus, stating: 

> USER_def_reax (may be required)

is incorrect.
- After I had a biomass objective function I could use for the draft reconstruction run I got the following error message:
```bash
Traceback (most recent call last):
  File "/tools/Architect/scripts/model_reconstruction/3_identify_gap_filling_candidates.py", line 139, in <module>
    model = utils.read_model_for_simulation(all_conf_and_candidate_file, objective_function)
  File "/tools/Architect/scripts/model_reconstruction/utils.py", line 211, in read_model_for_simulation
    model = read_cbmodel_from_file(input_file)
  File "/tools/Architect/dependency/framed/io/plaintext.py", line 68, in read_cbmodel_from_file
    return read_model_from_file(filename, 'cb')
  File "/tools/Architect/dependency/framed/io/plaintext.py", line 53, in read_model_from_file
    model.add_reaction_from_str(line, clear_tmp=False)
  File "/tools/Architect/dependency/framed/model/cbmodel.py", line 493, in add_reaction_from_str
    self._parser.parse_reaction(reaction_str, kind='cb')
  File "/tools/Architect/dependency/framed/model/parser.py", line 32, in parse_reaction
    raise SyntaxError('Unable to parse: ' + reaction_str)
SyntaxError: Unable to parse: DEADEND_HIGH_import_M_0.001:      M_0.001 <->     [-1000, 1000]
Traceback (most recent call last):
  File "/tools/Architect/dependency/CarveMe/scripts/gapfill", line 5, in <module>
    from carveme import config, project_dir
  File "/tools/Architect/dependency/CarveMe/carveme/__init__.py", line 14, in <module>
    set_default_solver(config.get('solver', 'default_solver'))
  File "/tools/Architect/dependency/framed/solvers/__init__.py", line 61, in set_default_solver
    raise EnvironmentError("Solver '{}' not available.".format(solvername))
OSError: Solver 'cplex' not available.
Traceback (most recent call last):
  File "/tools/Architect/scripts/model_reconstruction/x_verify_solns_necessary_and_sufficient.py", line 67, in <module>
    gap_filling_solns = utils.read_gap_filling_solns(gap_filling_sol_file)
  File "/tools/Architect/scripts/model_reconstruction/utils.py", line 258, in read_gap_filling_solns
    with open(gap_filling_solns_file) as reader:
FileNotFoundError: [Errno 2] No such file or directory: '/architect_run/organism/Model_reconstruction/temp/model_gapfilled_multi_0.lst'
Traceback (most recent call last):
  File "/tools/Architect/scripts/model_reconstruction/x_output_models_from_gapfill_soln.py", line 102, in <module>
    gap_filling_solns = utils.read_gap_filling_solns(gap_filling_sol_file)
  File "/tools/Architect/scripts/model_reconstruction/utils.py", line 258, in read_gap_filling_solns
    with open(gap_filling_solns_file) as reader:
FileNotFoundError: [Errno 2] No such file or directory: '/architect_run/organism/Model_reconstruction/temp/model_gapfilled_multi_0.lst'
```

For the part `SyntaxError: Unable to parse: DEADEND_HIGH_import_M_0.001:      M_0.001 <->     [-1000, 1000]`, I think I would need to change your code to remove this error as I never added this reaction. My `USER_defined_reactions.out` file contains only the biomass objective function which is the biomass reaction from CarveMe for gram-positive bacteria.
The `OSError: Solver 'cplex' not available.` should not occur as I installed cplex exactly like described in the installation guide on the GitHub README.

**Comment by nnursimulu** [comment]
Hello and apologies for the late reply.

Thank you for pointing out these issues with the README.  I will be fixing those.

The issue with PRIAM is that the website of its maintainers appears to still be down.  In the interim, I would suggest specifying to the downloader not to install PRIAM. 

Can you please check if you have extra characters (like tab delimiters) in your version of the USER_defined_reactions.out file?

**Comment by GwennyGit** [comment]
Thank you for the quick response.

I just came around to trying Architect again.

The issue with the cplex.bin file was that I had it not in the cplex folder, as the Dockerfile expects it, but in the Dockerfile folder, as described in the README. Even though the file is in the wrong directory, Docker does not report any error, and the user thinks everything is installed correctly. I only found the solution to this issue because I looked at the Dockerfile more closely.

As for the issue with the USER_defined_reactions.out file, it seems I accidentally wrote `M_0.001` as the stoichiometric value, which in turn led to the error.
